services:
  frontend:
    container_name: frontend
    build:
      context: ./game-store-app
    restart: always
    depends_on:
      - backend-api
      - backend-auth
    network_mode: host
  backend-api:
    container_name: backend-api
    build:
      context: ./game-store
    restart: always
    depends_on:
      - mongo
    network_mode: host
  backend-auth:
    container_name: backend-auth
    build: 
      context: ./authorization-server
    network_mode: host
    depends_on:
      - mongo

  mongo:
    network_mode: host
    image: mongo
    volumes:
      - ./mongo_data:/var/lib/mongodb
